#include "ft_printf.h"
#include "libft.h"
int main()
{
    /*
    //Simple %s
    printf("%s\n", "Hello");
    printf("%s\n", "");
    printf("%s\n", NULL);
    printf("a%sa\n", "Hello");
    printf("a%sa\n", "");
    printf("a%sa\n", NULL);
    printf("%s\n", "%15d\n");
    printf("%s\n", "Hello");
    printf("%s\n", "");
    printf("%s\n", NULL);
    printf("a%sa\n", "Hello");
    printf("a%sa\n", "");
    printf("a%sa\n", NULL);
    printf("%s\n", "%15d");
    printf("-------------------------------\n");
    ft_printf("%s\n", "Hello");
    ft_printf("%s\n", "");
    ft_printf("%s\n", NULL);
    ft_printf("a%sa\n", "Hello");
    ft_printf("a%sa\n", "");
    ft_printf("a%sa\n", NULL);
    ft_printf("%s\n", "%15d\n");
    ft_printf("%s\n", "Hello");
    ft_printf("%s\n", "");
    ft_printf("%s\n", NULL);
    ft_printf("a%sa\n", "Hello");
    ft_printf("a%sa\n", "");
    ft_printf("a%sa\n", NULL);
    ft_printf("%s\n", "%15d");
    //Simpe %s and Width

    printf("_________________________________________________________________________________________\n\n\n");

    ft_printf("'%2s'\n", "ABC");
    ft_printf("'%3s'\n", "ABC");
    ft_printf("'%4s'\n", "ABC");
    ft_printf("'a%4sa'\n", "ABC");
    ft_printf("'%1s'\n", NULL);
    ft_printf("'a%1sa'\n", NULL);
    ft_printf("'%6s'\n", NULL);
    ft_printf("'%7s'\n", NULL);
    ft_printf("'%4s'\n", "");
    ft_printf("'%1s'\n", "");
    ft_printf("'a%1sa'\n", "");
    printf("------------------------------\n");
    printf("'%2s'\n", "ABC");
    printf("'%3s'\n", "ABC");
    printf("'%4s'\n", "ABC");
    printf("'a%4sa'\n", "ABC");
    printf("'%1s'\n", NULL);
    printf("'a%1sa'\n", NULL);
    printf("'%6s'\n", NULL);
    printf("'%7s'\n", NULL);
    printf("'%4s'\n", "");
    printf("'%1s'\n", "");
    printf("'a%1sa'\n", "");
    //Simpe %s and -
    printf("_________________________________________________________________________________________\n\n\n");
       printf("'%-2s'\n", "ABC");
       printf("'%-3s'\n", "ABC");
       printf("'%-4s'\n", "ABC");
       printf("'a%-4sa'\n", "ABC");
       printf("'%-1s'\n", NULL);
       printf("'a%-1sa'\n", NULL);
       printf("'%-6s'\n", NULL);
       printf("'%-7s'\n", NULL);
       printf("'%-4s'\n", "");
       printf("'%-1s'\n", "");
       printf("'a%-1sa'\n", "");
       printf("__________________________________\n");
       ft_printf("'%-2s'\n", "ABC");
       ft_printf("'%-3s'\n", "ABC");
       ft_printf("'%-4s'\n", "ABC");
       ft_printf("'a%-4sa'\n", "ABC");
       ft_printf("'%-1s'\n", NULL);
       ft_printf("'a%-1sa'\n", NULL);
       ft_printf("'%-6s'\n", NULL);
       ft_printf("'%-7s'\n", NULL);
       ft_printf("'%-4s'\n", "");
       ft_printf("'%-1s'\n", "");
       ft_printf("'a%-1sa'\n", "");

       printf("_________________________________________________________________________________________\n\n\n");


       printf("'%2.3s'\n", "ABC");
       printf("'%3.3s'\n", "ABC");
       printf("'%4.3s'\n", "ABC");
       printf("'a%4.3sa'\n", "ABC");
       printf("'%1.3s'\n", NULL);
       printf("'a%1.3sa'\n", NULL);
       printf("'%6.3s'\n", NULL);
       printf("'%7.3s'\n", NULL);
       printf("'%4.3s'\n", "");
       printf("'%1.3s'\n", "");
       printf("'a%1.3sa'\n", "");
       printf("'%2.2s'\n", "ABC");
       printf("'%3.2s'\n", "ABC");
       printf("'%4.2s'\n", "ABC");
       printf("'a%4.2sa'\n", "ABC");
       printf("'%1.2s'\n", NULL);
       printf("'a%1.2sa'\n", NULL);
       printf("'%6.2s'\n", NULL);
       printf("'%7.2s'\n", NULL);
       printf("'%4.2s'\n", "");
       printf("'%1.2s'\n", "");
       printf("'a%1.2sa'\n", "");
       printf("'%2.10s'\n", "ABC");
       printf("'%3.10s'\n", "ABC");
       printf("'%4.10s'\n", "ABC");
       printf("'a%4.10sa'\n", "ABC");
       printf("'%1.10s'\n", NULL);
       printf("'a%1.10sa'\n", NULL);
       printf("'%6.10s'\n", NULL);
       printf("'%7.10s'\n", NULL);
       printf("'%4.10s'\n", "");
       printf("'%1.10s'\n", "");
       printf("'a%1.10sa'\n", "");
       printf("'%2.s'\n", "ABC");
       printf("'%3.s'\n", "ABC");
       printf("'%4.s'\n", "ABC");
       printf("'a%4.sa'\n", "ABC");
       printf("'%1.s'\n", NULL);
       printf("'a%1.sa'\n", NULL);
       printf("'%6.s'\n", NULL);
       printf("'%7.s'\n", NULL);
       printf("'%4.s'\n", "");
       printf("'%1.s'\n", "");
    printf("a%1.sa'\n", "");

    printf("________________________________\n");

    ft_printf("'%2.3s'\n", "ABC");
    ft_printf("'%3.3s'\n", "ABC");
    ft_printf("'%4.3s'\n", "ABC");
    ft_printf("'a%4.3sa'\n", "ABC");
    ft_printf("'%1.3s'\n", NULL);
    ft_printf("'a%1.3sa'\n", NULL);
    ft_printf("'%6.3s'\n", NULL);
    ft_printf("'%7.3s'\n", NULL);
    ft_printf("'%4.3s'\n", "");
    ft_printf("'%1.3s'\n", "");
    ft_printf("'a%1.3sa'\n", "");
    ft_printf("'%2.2s'\n", "ABC");
    ft_printf("'%3.2s'\n", "ABC");
    ft_printf("a%*.*sa\n", 7,2, "ABC");
    SP("printfESprintfS","--> \"%%s\" * part2 ;)\n");
    ft_printf("'%4.2s'\n", "ABC");
    ft_printf("'a%4.2sa'\n", "ABC");
    ft_printf("'%1.2s'\n", NULL);
    ft_printf("'a%1.2sa'\n", NULL);
    ft_printf("'%6.2s'\n", NULL);
    ft_printf("'%7.2s'\n", NULL);
    ft_printf("'%4.2s'\n", "");
    ft_printf("'%1.2s'\n", "");
    ft_printf("'a%1.2sa'\n", "");
    ft_printf("'%2.10s'\n", "ABC");
    ft_printf("'%3.10s'\n", "ABC");
    ft_printf("'%4.10s'\n", "ABC");
    ft_printf("'a%4.10sa'\n", "ABC");
    ft_printf("'%1.10s'\n", NULL);
    ft_printf("'a%1.10sa'\n", NULL);
    ft_printf("'%6.10s'\n", NULL);
    ft_printf("'%7.10s'\n", NULL);
    ft_printf("'%4.10s'\n", "");
    ft_printf("'%1.10s'\n", "");
    ft_printf("'a%1.10sa'\n", "");
    ft_printf("'%2.s'\n", "ABC");
    ft_printf("'%3.s'\n", "ABC");
    ft_printf("'%4.s'\n", "ABC");
    ft_printf("'a%4.sa'\n", "ABC");
    ft_printf("'%1.s'\n", NULL);
    ft_printf("'a%1.sa'\n", NULL);
    ft_printf("'%6.s'\n", NULL);
    ft_printf("'%7.s'\n", NULL);
    ft_printf("'%4.s'\n", "");
    ft_printf("'%1.s'\n", "");
    ft_printf("'a%1.sa'\n", "");
    printf("'%2.s'\n", "ABC");
    */

    printf("%.3s\n", "ABC");
    printf("%.3s\n", "ABC");
    printf("%.3s\n", "ABC");
    printf("a%.3sa\n", "ABC");
    printf("%.3s\n", NULL);
    printf("a%.3sa\n", NULL);
    printf("%.3s\n", NULL);
    printf("%.3s\n", NULL);
    printf("%.3s\n", "");
    printf("%.3s\n", "");
    printf("a%.3sa\n", "");
    printf("%.2s\n", "ABC");
    printf("%.2s\n", "ABC");
    printf("%.2s\n", "ABC");
    printf("a%.2sav", "ABC");
    printf("%.2s\n", NULL);
    printf("a%.2sav", NULL);
    printf("%.2s\n", NULL);
    printf("%.2s\n", NULL);
    printf("%.2s\n", "");
    printf("%.2s\n", "");
    printf("a%.2sa\n", "");
    printf("%.10s\n", "ABC");
    printf("%.10s\n", "");
    printf("%.10s\n", "ABC");
    printf("%.10s\n", "ABC");
    printf("a%.10sa\n", "ABC");
    printf("%.10s\n", NULL);
    printf("a%.10sa\n", NULL);
    printf("%.10s\n", NULL);
    printf("%.10s\n", NULL);
    printf("%.10s\n", "");
    printf("%.10s\n", "");
    printf("a%.10sa\n", "");
    printf("%.s\n", "ABC");
    printf("%.s\n", "ABC");
    printf("%.s\n", "ABC");
    printf("a%.sa\n", "ABC");
    printf("%.s\n", NULL);
    printf("a%.sa\n", NULL);
    printf("%.s\n", NULL);
    printf("%.s\n", NULL);
    printf("%.s\n", "");
    printf("%.s\n", "");
    printf("a%.sa\n", "");
    printf("%*.3s\n", 5, "ABC");
    printf("%*.3s\n", 5, "ABC");
    printf("%*.3s\n", 5, "ABC");
    printf("a%*.3sa\n", 5, "ABC");
    printf("%*.3s\n", 5, NULL);
    printf("a%*.3sa\n", 5, NULL);
    printf("%*.3s\n", 5, NULL);
    printf("%*.3s\n", 5, NULL);
    printf("%*.3s\n", 5, "");
    printf("%*.3s\n", 5, "");
    printf("a%*.3sa\n", 5, "");
    printf("%*.2s\n", 5, "ABC");
    printf("%*.2s\n", 5, "ABC");
    printf("%*.2s\n", 5, "ABC");
    printf("a%*.2sa\n", 5, "ABC");

    printf("%*.3s\n", 0, "ABC");
    printf("%*.3s\n", 0, "ABC");
    printf("%*.3s\n", 0, "ABC");
    printf("a%*.3sa\n", 0, "ABC");
    printf("%*.3s\n", 0, NULL);
    printf("a%*.3sa\n", 0, NULL);
    printf("%*.3s\n", 0, NULL);
    printf("%*.3s\n", 0, NULL);
    printf("%*.3s\n", 0, "");
    printf("%*.3s\n", 0, "");
    printf("a%*.3sa\n", 0, "");
    printf("%*.2s\n", 0, "ABC");
    printf("%*.2s\n", 0, "ABC");
    printf("%*.2s\n", 0, "ABC");
    printf("a%*.2sa\n", 0, "ABC");

    printf("%*.3s\n", -15, "ABC");
    printf("%*.3s\n", -15, "ABC");
    printf("%*.3s\n", -15, "ABC");
    printf("a%*.3sa\n", -15, "ABC");
    printf("%*.3s\n", -15, NULL);
    printf("a%*.3sa\n", -15, NULL);
    printf("%*.3s\n", -15, NULL);
    printf("%.10s\n", "");
    printf("%*.3s\n", -15, NULL);
    printf("%*.3s\n", -15, "");
    printf("%*.3s\n", -15, "");
    printf("a%*.3sa\n", -15, "");
    printf("%*.2s\n", -15, "ABC");
    printf("%*.2s\n", -15, "ABC");
    printf("%*.2s\n", -15, "ABC");
    printf("a%*.2sa\n", -15, "ABC");
    printf("%.*s\n", 5, "ABC");
    printf("%.*s\n", 5, "ABC");
    printf("%.*s\n", 5, "ABC");
    printf("a%.*sa\n", 5, "ABC");
    printf("%.*s\n", 5, NULL);
    printf("a%.*sa\n", 5, NULL);
    printf("%.*s\n", 5, NULL);
    printf("%.*s\n", 5, NULL);
    printf("%.*s\n", 5, "");
    printf("%.*s\n", 5, "");
    printf("a%.*sa\n", 5, "");
    printf("%.*s\n", 5, "ABC");
    printf("%.*s\n", 5, "ABC");
    printf("%.*s\n", 5, "ABC");
    printf("a%.*sa\n", 5, "ABC");

    printf("%.*s\n", -5, "ABC");
    printf("%.*s\n", -5, "ABC");
    printf("%.*s\n", -5, "ABC");
    printf("a%.*sa\n", -5, "ABC");
    printf("%.*s\n", -5, NULL);
    printf("a%.*sa\n", -5, NULL);
    printf("%.*s\n", -5, NULL);
    printf("%.*s\n", -5, NULL);
    printf("%.*s\n", -5, "");
    printf("%.*s\n", -5, "");
    printf("a%.*sa\n", -5, "");
    printf("%.*s\n", -5, "ABC");
    printf("%.*s\n", -5, "ABC");
    printf("%.*s\n", -5, "ABC");
    printf("a%.*sa\n", -5, "ABC");

    printf("%*.*s\n", 7,2, "ABC");
    printf("%.10s\n", "");
    printf("%*.*s\n", 7,2, "ABC");
    printf("%*.*s\n", 7,2, "ABC");
    printf("a%*.*sa\n", 7,2, "ABC");
    printf("%*.*s\n", 7,2, NULL);
    printf("a%*.*sa\n", 7,2, NULL);
    printf("%*.*s\n", 7,2, NULL);
    printf("%*.*s\n", 7,2, NULL);
    printf("%*.*s\n", 7,2, "");
    printf("%*.*s\n", 7,2, "");
    printf("a%*.*sa\n", 7,2, "");
    printf("%*.*s\n", 7,2, "ABC");
    printf("%*.*s\n", 7,2, "ABC");
    printf("%*.*s\n", 7,2, "ABC");
    printf("a%*.*sa\n", 7,2, "ABC");
    printf("___________________________________\n");
    ft_printf("%.3s\n", "ABC");
    ft_printf("%.3s\n", "ABC");
    ft_printf("%.3s\n", "ABC");
    ft_printf("a%.3sa\n", "ABC");
    ft_printf("%.3s\n", NULL);
    ft_printf("a%.3sa\n", NULL);
    ft_printf("%.3s\n", NULL);
    ft_printf("%.3s\n", NULL);
    ft_printf("%.3s\n", "");
    ft_printf("%.3s\n", "");
    ft_printf("a%.3sa\n", "");
    ft_printf("%.2s\n", "ABC");
    ft_printf("%.2s\n", "ABC");
    ft_printf("%.2s\n", "ABC");
    ft_printf("a%.2sav", "ABC");
    ft_printf("%.2s\n", NULL);
    ft_printf("a%.2sav", NULL);
    ft_printf("%.2s\n", NULL);
    ft_printf("%.2s\n", NULL);
    ft_printf("%.2s\n", "");
    ft_printf("%.2s\n", "");
    ft_printf("a%.2sa\n", "");
    ft_printf("%.10s\n", "ABC");
    ft_printf("%.10s\n", "");
    ft_printf("%.10s\n", "ABC");
    ft_printf("%.10s\n", "ABC");
    ft_printf("a%.10sa\n", "ABC");
    ft_printf("%.10s\n", NULL);
    ft_printf("a%.10sa\n", NULL);
    ft_printf("%.10s\n", NULL);
    ft_printf("%.10s\n", NULL);
    ft_printf("%.10s\n", "");
    ft_printf("%.10s\n", "");
    ft_printf("a%.10sa\n", "");
    ft_printf("%.s\n", "ABC");
    ft_printf("%.s\n", "ABC");
    ft_printf("%.s\n", "ABC");
    ft_printf("a%.sa\n", "ABC");
    ft_printf("%.s\n", NULL);
    ft_printf("a%.sa\n", NULL);
    ft_printf("%.s\n", NULL);
    ft_printf("%.s\n", NULL);
    ft_printf("%.s\n", "");
    ft_printf("%.s\n", "");
    ft_printf("a%.sa\n", "");
    ft_printf("%*.3s\n", 5, "ABC");
    ft_printf("%*.3s\n", 5, "ABC");
    ft_printf("%*.3s\n", 5, "ABC");
    ft_printf("a%*.3sa\n", 5, "ABC");
    ft_printf("%*.3s\n", 5, NULL);
    ft_printf("a%*.3sa\n", 5, NULL);
    ft_printf("%*.3s\n", 5, NULL);
    ft_printf("%*.3s\n", 5, NULL);
    ft_printf("%*.3s\n", 5, "");
    ft_printf("%*.3s\n", 5, "");
    ft_printf("a%*.3sa\n", 5, "");
    ft_printf("%*.2s\n", 5, "ABC");
    ft_printf("%*.2s\n", 5, "ABC");
    ft_printf("%*.2s\n", 5, "ABC");
    ft_printf("a%*.2sa\n", 5, "ABC");

    ft_printf("%*.3s\n", 0, "ABC");
    ft_printf("%*.3s\n", 0, "ABC");
    ft_printf("%*.3s\n", 0, "ABC");
    ft_printf("a%*.3sa\n", 0, "ABC");
    ft_printf("%*.3s\n", 0, NULL);
    ft_printf("a%*.3sa\n", 0, NULL);
    ft_printf("%*.3s\n", 0, NULL);
    ft_printf("%*.3s\n", 0, NULL);
    ft_printf("%*.3s\n", 0, "");
    ft_printf("%*.3s\n", 0, "");
    ft_printf("a%*.3sa\n", 0, "");
    ft_printf("%*.2s\n", 0, "ABC");
    ft_printf("%*.2s\n", 0, "ABC");
    ft_printf("%*.2s\n", 0, "ABC");
    ft_printf("a%*.2sa\n", 0, "ABC");

    ft_printf("%*.3s\n", -15, "ABC");
    ft_printf("%*.3s\n", -15, "ABC");
    ft_printf("%*.3s\n", -15, "ABC");
    ft_printf("a%*.3sa\n", -15, "ABC");
    ft_printf("%*.3s\n", -15, NULL);
    ft_printf("a%*.3sa\n", -15, NULL);
    ft_printf("%*.3s\n", -15, NULL);
    ft_printf("%.10s\n", "");
    ft_printf("%*.3s\n", -15, NULL);
    ft_printf("%*.3s\n", -15, "");
    ft_printf("%*.3s\n", -15, "");
    ft_printf("a%*.3sa\n", -15, "");
    ft_printf("%*.2s\n", -15, "ABC");
    ft_printf("%*.2s\n", -15, "ABC");
    ft_printf("%*.2s\n", -15, "ABC");
    ft_printf("a%*.2sa\n", -15, "ABC");
    ft_printf("%.*s\n", 5, "ABC");
    ft_printf("%.*s\n", 5, "ABC");
    ft_printf("%.*s\n", 5, "ABC");
    ft_printf("a%.*sa\n", 5, "ABC");
    ft_printf("%.*s\n", 5, NULL);
    ft_printf("a%.*sa\n", 5, NULL);
    ft_printf("%.*s\n", 5, NULL);
    ft_printf("%.*s\n", 5, NULL);
    ft_printf("%.*s\n", 5, "");
    ft_printf("%.*s\n", 5, "");
    ft_printf("a%.*sa\n", 5, "");
    ft_printf("%.*s\n", 5, "ABC");
    ft_printf("%.*s\n", 5, "ABC");
    ft_printf("%.*s\n", 5, "ABC");
    ft_printf("a%.*sa\n", 5, "ABC");

    ft_printf("%.*s\n", -5, "ABC");
    ft_printf("%.*s\n", -5, "ABC");
    ft_printf("%.*s\n", -5, "ABC");
    ft_printf("a%.*sa\n", -5, "ABC");
    ft_printf("%.*s\n", -5, NULL);
    ft_printf("a%.*sa\n", -5, NULL);
    ft_printf("%.*s\n", -5, NULL);
    ft_printf("%.*s\n", -5, NULL);
    ft_printf("%.*s\n", -5, "");
    ft_printf("%.*s\n", -5, "");
    ft_printf("a%.*sa\n", -5, "");
    ft_printf("%.*s\n", -5, "ABC");
    ft_printf("%.*s\n", -5, "ABC");
    ft_printf("%.*s\n", -5, "ABC");
    ft_printf("a%.*sa\n", -5, "ABC");

    ft_printf("%*.*s\n", 7,2, "ABC");
    ft_printf("%.10s\n", "");
    ft_printf("%*.*s\n", 7,2, "ABC");
    ft_printf("%*.*s\n", 7,2, "ABC");
    ft_printf("a%*.*sa\n", 7,2, "ABC");
    ft_printf("%*.*s\n", 7,2, NULL);
    ft_printf("a%*.*sa\n", 7,2, NULL);
    ft_printf("%*.*s\n", 7,2, NULL);
    ft_printf("%*.*s\n", 7,2, NULL);
    ft_printf("%*.*s\n", 7,2, "");
    ft_printf("%*.*s\n", 7,2, "");
    ft_printf("a%*.*sa\n", 7,2, "");
    ft_printf("%*.*s\n", 7,2, "ABC");
    ft_printf("%*.*s\n", 7,2, "ABC");
    ft_printf("%*.*s\n", 7,2, "ABC");
    ft_printf("a%*.*sa\n", 7,2, "ABC");
    return (0);
}
